In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
# loading the training and testing data
ccpp_train = np.genfromtxt('ccpp_x_y_train.csv', delimiter = ',')
x_train = ccpp_train[:, 0:ccpp_train.shape[1]-1]
y_train = ccpp_train[:, ccpp_train.shape[1]-1]
x_test = np.genfromtxt("ccpp_x_test.csv", delimiter = ",")

In [3]:
# printing the data
print(ccpp_train)

[[   8.58   38.38 1021.03   84.37  482.26]
 [  21.79   58.2  1017.21   66.74  446.94]
 [  16.64   48.92 1011.55   78.76  452.56]
 ...
 [  29.8    69.34 1009.36   64.74  437.65]
 [  16.37   54.3  1017.94   63.63  459.97]
 [  30.11   62.04 1010.69   47.96  444.42]]


In [4]:
# adding dummy data to training data
df = pd.DataFrame(x_train)
N = x_train.shape[1]
count =1
for i in range(N):
    for j in range(i, N):
        df[count] = df[df.columns[i]] * df[df.columns[j]]
        count += 1

for i in range(N):
    for j in range(i, N):
        for k in range(j, N):
            df[count] = df[df.columns[i]]*df[df.columns[j]]*df[df.columns[k]]
            count += 1

x_train = df.values

# adding dummy data to testing data
df = pd.DataFrame(x_test)
N = x_test.shape[1]
count =1
for i in range(N):
    for j in range(i, N):
        df[count] = df[df.columns[i]] * df[df.columns[j]]
        count += 1

for i in range(N):
    for j in range(i, N):
        for k in range(j, N):
            df[count] = df[df.columns[i]]*df[df.columns[j]]*df[df.columns[k]]
            count += 1

x_test = df.values

In [5]:
# feature Scaling
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [6]:
# step_gradient - find the new regression coefficients
def step_gradient(x, y, learning_rate, m):
    M = x.shape[0]
    m_slope = (-2/M)*(((y - (x*m).sum(axis=1)).reshape(-1, 1))*x).sum(axis=0)
    m = m - learning_rate * m_slope
    return m

In [7]:
# generic_gd - calculate regression coefficient with specified learning_rate and num_iterations
def generic_gd(x, y, learning_rate, num_iterations):
    m = np.zeros(x.shape[1])
    for i in range(num_iterations):
        m = step_gradient(x, y, learning_rate, m)
        print(i, "Cost :", cost(x, y, m))
    return m

In [8]:
# cost - finding the error on trainig_data
def cost(x, y, m):
    return ((y - (x*m).sum(axis=1)) ** 2).mean()

In [9]:
# run - run gradient descent on training data
def run(x, y):
    df = pd.DataFrame(x)
    df[x.shape[1]] = 1
    x = df.values
    learning_rate = 0.009
    num_iterations = 1000
    m = generic_gd(x, y, learning_rate, num_iterations)
    print(m)
    return m
m = run(x_train, y_train)

0 Cost : 199316.62803392168
1 Cost : 192181.65286189417
2 Cost : 185319.71312602583
3 Cost : 178706.7686780351
4 Cost : 172330.75010614117
5 Cost : 166182.49187618188
6 Cost : 160253.70605348563
7 Cost : 154536.52311605553
8 Cost : 149023.38179800153
9 Cost : 143706.99688983784
10 Cost : 138580.34466178046
11 Cost : 133636.65247373437
12 Cost : 128869.3895724245
13 Cost : 124272.2583990199
14 Cost : 119839.18624785978
15 Cost : 115564.31723231214
16 Cost : 111442.00453978844
17 Cost : 107466.80296401307
18 Cost : 103633.4617042835
19 Cost : 99936.91742209315
20 Cost : 96372.2875458934
21 Cost : 92934.86381511597
22 Cost : 89620.10605489629
23 Cost : 86423.63617324762
24 Cost : 83341.23237272947
25 Cost : 80368.82356893996
26 Cost : 77502.48400843612
27 Cost : 74738.4280789506
28 Cost : 72073.0053050293
29 Cost : 69502.69552245963
30 Cost : 67024.10422509749
31 Cost : 64633.95807792882
32 Cost : 62329.10059042314
33 Cost : 60106.48794444836
34 Cost : 57963.18497122203
35 Cost : 55896.36

291 Cost : 35.81027513824575
292 Cost : 35.6082339135871
293 Cost : 35.412769952723195
294 Cost : 35.223651108319075
295 Cost : 35.04065350520813
296 Cost : 34.863561245312056
297 Cost : 34.69216612308811
298 Cost : 34.52626735112877
299 Cost : 34.3656712955492
300 Cost : 34.21019122081678
301 Cost : 34.05964704368295
302 Cost : 33.91386509589379
303 Cost : 33.77267789536627
304 Cost : 33.63592392552743
305 Cost : 33.503447422526676
306 Cost : 33.37509817003811
307 Cost : 33.25073130138502
308 Cost : 33.13020710872196
309 Cost : 33.01339085902546
310 Cost : 32.900152616648974
311 Cost : 32.790367072207985
312 Cost : 32.68391337757074
313 Cost : 32.58067498673404
314 Cost : 32.480539502377376
315 Cost : 32.38339852789063
316 Cost : 32.28914752468045
317 Cost : 32.197685674567765
318 Cost : 32.10891574709418
319 Cost : 32.02274397156189
320 Cost : 31.939079913639013
321 Cost : 31.85783635636657
322 Cost : 31.778929185411002
323 Cost : 31.702277278410033
324 Cost : 31.627802398266194
325 

571 Cost : 27.33824765566695
572 Cost : 27.331703750770412
573 Cost : 27.325186001525754
574 Cost : 27.318694296156128
575 Cost : 27.31222852360976
576 Cost : 27.30578857354706
577 Cost : 27.299374336328107
578 Cost : 27.292985703000596
579 Cost : 27.286622565288038
580 Cost : 27.280284815578483
581 Cost : 27.273972346913474
582 Cost : 27.267685052977402
583 Cost : 27.261422828087177
584 Cost : 27.255185567182213
585 Cost : 27.248973165814736
586 Cost : 27.242785520140373
587 Cost : 27.236622526909045
588 Cost : 27.230484083456084
589 Cost : 27.224370087693703
590 Cost : 27.218280438102656
591 Cost : 27.212215033724142
592 Cost : 27.206173774152013
593 Cost : 27.200156559525162
594 Cost : 27.19416329052011
595 Cost : 27.188193868343895
596 Cost : 27.182248194727084
597 Cost : 27.176326171917008
598 Cost : 27.170427702671244
599 Cost : 27.16455269025121
600 Cost : 27.15870103841594
601 Cost : 27.152872651416175
602 Cost : 27.147067433988344
603 Cost : 27.141285291349046
604 Cost : 27.13

864 Cost : 26.203328440205905
865 Cost : 26.20128165604579
866 Cost : 26.199242944222835
867 Cost : 26.197212272680286
868 Cost : 26.195189609488803
869 Cost : 26.19317492284584
870 Cost : 26.19116818107526
871 Cost : 26.18916935262674
872 Cost : 26.187178406075333
873 Cost : 26.185195310120942
874 Cost : 26.18322003358781
875 Cost : 26.18125254542405
876 Cost : 26.179292814701167
877 Cost : 26.17734081061351
878 Cost : 26.175396502477852
879 Cost : 26.173459859732837
880 Cost : 26.171530851938577
881 Cost : 26.169609448776068
882 Cost : 26.16769562004681
883 Cost : 26.165789335672258
884 Cost : 26.163890565693368
885 Cost : 26.16199928027013
886 Cost : 26.16011544968109
887 Cost : 26.158239044322873
888 Cost : 26.156370034709713
889 Cost : 26.154508391473005
890 Cost : 26.15265408536081
891 Cost : 26.15080708723741
892 Cost : 26.14896736808284
893 Cost : 26.147134898992444
894 Cost : 26.145309651176383
895 Cost : 26.14349159595922
896 Cost : 26.14168070477942
897 Cost : 26.13987694918

In [10]:
# predict - predicting values for x_test
def predict(x,m):
    return (x*m).sum(axis=1)

In [11]:
df = pd.DataFrame(x_test)
df[x_test.shape[1]] = 1
x_test = df.values
y_pred = predict(x_test, m)
print(y_pred)

[472.12824565 471.8653367  437.29587881 ... 442.16642059 444.00820369
 448.1320055 ]


In [12]:
np.savetxt('Predictions_ccpp.csv',y_pred, fmt = "%.8f")