In [1]:
import numpy as np
import pandas as pd

In [2]:
# loading the training and testing data
ccpp_train = np.genfromtxt('ccpp_x_y_train.csv', delimiter = ',')
x_train = ccpp_train[:, 0:ccpp_train.shape[1]-1]
y_train = ccpp_train[:, ccpp_train.shape[1]-1]
x_test = np.genfromtxt("ccpp_x_test.csv", delimiter = ",")

In [3]:
# printing the data
print(ccpp_train)

[[   8.58   38.38 1021.03   84.37  482.26]
 [  21.79   58.2  1017.21   66.74  446.94]
 [  16.64   48.92 1011.55   78.76  452.56]
 ...
 [  29.8    69.34 1009.36   64.74  437.65]
 [  16.37   54.3  1017.94   63.63  459.97]
 [  30.11   62.04 1010.69   47.96  444.42]]
